// Lista predefinita di strumenti suonati live.
// I generi sono gestiti via DB (tabella `genres`) dal superadmin.
export const INSTRUMENT_OPTIONS = [
  "Voce",
  "Cori",
  "Chitarra acustica",
  "Chitarra elettrica",
  "Chitarra classica",
  "Basso",
  "Contrabbasso",
  "Pianoforte",
  "Tastiere",
  "Organo",
  "Synth",
  "Batteria",
  "Percussioni",
  "Cajón",
  "Sax",
  "Tromba",
  "Trombone",
  "Flauto traverso",
  "Clarinetto",
  "Violino",
  "Viola",
  "Violoncello",
  "Arpa",
  "Fisarmonica",
  "Armonica",
  "DJ / controller",
  "Loop station",
] as const;
